- name: Configure SSH and Samba on Ubuntu
  hosts: testservers
  become: yes
  tasks:

    ### 🔐 SSH Configuration
    - name: Ensure OpenSSH is installed
      apt:
        name: openssh-server
        state: present
        update_cache: yes

    - name: Enable password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'

        line: 'PasswordAuthentication yes'

        state: present

    - name: Allow root login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'

        line: 'PermitRootLogin yes'

        state: present

    - name: Restart SSH service
      service:
        name: ssh
        state: restarted

    ### 📁 Samba Configuration
    - name: Install Samba
      apt:
        name: samba
        state: present
        update_cache: yes

    - name: Create Samba share directory
      file:
        path: /srv/samba/pi20
        state: directory
        mode: '0777'
        owner: nobody
        group: nogroup

    - name: Add Samba share to smb.conf
      blockinfile:
        path: /etc/samba/smb.conf
        block: |
          [pi20]
          path = /srv/samba/pi20
          browseable = yes
          read only = no
          guest ok = yes
          force user = nobody
          force group = nogroup
          hosts allow = 192.168.0.0/16

    - name: Restart Samba service
      service:
        name: smbd
        state: restarted





